export type TechPage = {
  slug: string;
  name: string;
  description: string;
  use: string;
  proof: string[];
  related: { href: string; label: string }[];
};

export const techPages: TechPage[] = [
  {
    slug: "react-native",
    name: "React Native",
    description: "Kush Gangwal uses React Native for Potato Bazaar, Tybee Go, and Findanio on Android and iOS.",
    use: "Production mobile clients, navigation, pagination, and store releases.",
    proof: ["Potato Bazaar Android and iOS", "Tybee Go", "Findanio", "SK Groups Play Console and Xcode releases"],
    related: [
      { href: "/kush-gangwal-react-native-developer", label: "React Native developer" },
      { href: "/projects/potato-bazaar", label: "Potato Bazaar" },
    ],
  },
  {
    slug: "react",
    name: "React.js",
    description: "Kush Gangwal uses React.js for Nexus, Scalelr, Potato Bazaar web, Findanio, and Macfolio.",
    use: "Product interfaces, feeds, search, and the Macfolio desktop UI.",
    proof: ["Nexus client", "Scalelr", "Potato Bazaar web", "Macfolio"],
    related: [{ href: "/kush-gangwal-react-developer", label: "React developer" }],
  },
  {
    slug: "nextjs",
    name: "Next.js",
    description: "Kush Gangwal uses Next.js for Macfolio, Potato Bazaar, Findanio, and Resumind.",
    use: "App Router pages, static case studies, and web product shells.",
    proof: ["kushgangwal.vercel.app", "Potato Bazaar web", "Findanio", "Resumind"],
    related: [{ href: "/kush-gangwal-nextjs-developer", label: "Next.js developer" }],
  },
  {
    slug: "nodejs",
    name: "Node.js",
    description: "Kush Gangwal uses Node.js for Nexus, Potato Bazaar, CodeMace, and Protonshub APIs.",
    use: "REST APIs behind web and React Native clients.",
    proof: ["Nexus API", "Potato Bazaar services", "CodeMace", "Protonshub apps"],
    related: [{ href: "/kush-gangwal-nodejs-developer", label: "Node.js developer" }],
  },
  {
    slug: "express",
    name: "Express.js",
    description: "Kush Gangwal uses Express.js for Node HTTP APIs, including CRUD practice and product backends.",
    use: "Route handlers and REST endpoints in Node services.",
    proof: ["Express and PostgreSQL CRUD API on GitHub", "Node services beside React clients"],
    related: [{ href: "/stack/nodejs", label: "Node.js" }],
  },
  {
    slug: "javascript",
    name: "JavaScript",
    description: "Kush Gangwal's web and mobile work is JavaScript, with TypeScript on newer products.",
    use: "React, Next.js, Node, and early internship code at Django Softwares.",
    proof: ["Scalelr", "Nexus", "CodSoft and Octanet web tasks"],
    related: [{ href: "/kush-gangwal-javascript-developer", label: "JavaScript developer" }],
  },
  {
    slug: "typescript",
    name: "TypeScript",
    description: "Kush Gangwal uses TypeScript on Tybee Go, Macfolio, CodeMace, and Resumind.",
    use: "Typed clients, review payloads, and resume report JSON.",
    proof: ["Tybee Go", "Macfolio", "CodeMace", "Resumind"],
    related: [{ href: "/kush-gangwal-typescript-developer", label: "TypeScript developer" }],
  },
  {
    slug: "java",
    name: "Java",
    description: "Kush Gangwal uses Java for OOP and DSA. Spring Boot is a current learning track.",
    use: "Computer science coursework and algorithm practice, not the production API stack.",
    proof: ["Medicaps University CST", "DSA practice", "Spring Boot on the learning list"],
    related: [{ href: "/kush-gangwal-java-developer", label: "Java developer" }],
  },
  {
    slug: "spring-boot",
    name: "Spring Boot",
    description: "Kush Gangwal is learning Spring Boot. Shipped backends today are Node.js.",
    use: "Study alongside system design and Java backend development.",
    proof: ["Listed on /now under learning"],
    related: [{ href: "/kush-gangwal-spring-boot", label: "Spring Boot note" }],
  },
  {
    slug: "mongodb",
    name: "MongoDB",
    description: "Kush Gangwal used MongoDB at Protonshub Technologies and Django Softwares.",
    use: "Document storage for full stack internship apps and Scalelr.",
    proof: ["Protonshub Next.js and Node apps", "Scalelr"],
    related: [{ href: "/work/protonshub-technologies", label: "Protonshub" }],
  },
  {
    slug: "postgresql",
    name: "PostgreSQL",
    description: "Kush Gangwal uses PostgreSQL for Macfolio's assistant data and for CodeMace.",
    use: "Durable records for reviews, analytics, and contact flow.",
    proof: ["Macfolio", "CodeMace", "SK Groups data work"],
    related: [{ href: "/projects/codemace", label: "CodeMace" }],
  },
  {
    slug: "sqlite",
    name: "SQLite",
    description: "Kush Gangwal used SQLite as the first database for Nexus on Vercel.",
    use: "A small durable store for offers, sessions, and ratings.",
    proof: ["Nexus"],
    related: [{ href: "/projects/nexus", label: "Nexus" }],
  },
  {
    slug: "rest-apis",
    name: "REST APIs",
    description: "Kush Gangwal designs REST APIs shared by React web apps and React Native clients.",
    use: "Pagination, auth-protected resources, and mobile-friendly payloads.",
    proof: ["Potato Bazaar", "Tybee Go", "Nexus", "Protonshub apps"],
    related: [{ href: "/kush-gangwal-backend-developer", label: "Backend developer" }],
  },
  {
    slug: "tailwind-css",
    name: "Tailwind CSS",
    description: "Kush Gangwal uses Tailwind CSS on Scalelr and Macfolio.",
    use: "Product UI and the macOS-style desktop styling.",
    proof: ["Scalelr", "Macfolio"],
    related: [{ href: "/projects/macfolio", label: "Macfolio" }],
  },
  {
    slug: "auth0",
    name: "Auth0",
    description: "Kush Gangwal used Auth0 for sign-in on Nexus instead of a custom password store.",
    use: "Protected routes for skill sessions and ratings.",
    proof: ["Nexus"],
    related: [{ href: "/projects/nexus", label: "Nexus" }],
  },
  {
    slug: "vercel",
    name: "Vercel",
    description: "Kush Gangwal deploys Next.js work on Vercel, including this portfolio and early Nexus.",
    use: "Hosting for kushgangwal.vercel.app and static project pages.",
    proof: ["kushgangwal.vercel.app", "Nexus"],
    related: [{ href: "/about-kush-gangwal", label: "About" }],
  },
  {
    slug: "github",
    name: "GitHub",
    description: "Kush Gangwal's GitHub is github.com/kush1905, plus github.com/Kush-PB for Potato Bazaar.",
    use: "Source control, profile README, and repository history.",
    proof: ["kush1905", "Kush-PB", "Nexus", "MacFolio"],
    related: [{ href: "/kush-gangwal-github", label: "GitHub profile" }],
  },
  {
    slug: "git",
    name: "Git",
    description: "Kush Gangwal uses Git on every internship and at SK Groups.",
    use: "Branching, review, and release history.",
    proof: ["SK Groups", "Protonshub", "Django Softwares"],
    related: [{ href: "/stack/github", label: "GitHub" }],
  },
  {
    slug: "posthog",
    name: "PostHog",
    description: "Kush Gangwal integrates PostHog in production apps at SK Groups.",
    use: "Product analytics beside Mixpanel on mobile and web.",
    proof: ["SK Groups releases"],
    related: [{ href: "/work/sk-groups", label: "SK Groups" }],
  },
  {
    slug: "mixpanel",
    name: "Mixpanel",
    description: "Kush Gangwal integrates Mixpanel for product analytics at SK Groups.",
    use: "Event tracking on shipped mobile and web features.",
    proof: ["SK Groups"],
    related: [{ href: "/blog/mixpanel-integration-react-native", label: "Mixpanel note" }],
  },
  {
    slug: "openai-api",
    name: "OpenAI API",
    description: "Kush Gangwal uses OpenAI APIs for structured AI features such as Resumind's review JSON.",
    use: "Schema-bound model calls, not an untyped chat paste.",
    proof: ["Resumind", "HCL Tech Full Stack Developer with AI"],
    related: [{ href: "/projects/resumind", label: "Resumind" }],
  },
  {
    slug: "ai-integrations",
    name: "AI Integrations",
    description: "Kush Gangwal integrates AI APIs in React Native and web products at SK Groups and on Potato Bazaar.",
    use: "Speech, maps-adjacent insights, crop insights, and resume analysis.",
    proof: ["Sarvam AI", "TTS and STT", "Potato Bazaar crop insights", "Resumind"],
    related: [{ href: "/kush-gangwal-ai-application-developer", label: "AI application developer" }],
  },
  {
    slug: "android-development",
    name: "Android Development",
    description: "Kush Gangwal ships Android builds with React Native, Android Studio, and Play Console.",
    use: "Debugging, release tracks, and Play Store submission for Potato Bazaar and other SK Groups apps.",
    proof: ["Potato Bazaar on Google Play", "SK Groups Android releases"],
    related: [{ href: "/potato-bazaar-app", label: "Potato Bazaar app" }],
  },
  {
    slug: "ios-development",
    name: "iOS Development",
    description: "Kush Gangwal ships iOS builds with React Native, Xcode, and Apple Developer.",
    use: "Signing, device debugging, and App Store release steps beside Android.",
    proof: ["Potato Bazaar iOS", "Tybee Go", "SK Groups Apple Developer releases"],
    related: [{ href: "/kush-gangwal-react-native-developer", label: "React Native developer" }],
  },
  {
    slug: "mobile-app-development",
    name: "Mobile App Development",
    description: "Kush Gangwal's mobile app development is React Native across Potato Bazaar, Tybee Go, and Findanio.",
    use: "Shared TypeScript UI, native release tooling, and REST clients.",
    proof: ["Potato Bazaar", "Tybee Go", "Findanio"],
    related: [{ href: "/kush-gangwal-mobile-app-developer", label: "Mobile app developer" }],
  },
];

export function techBySlug(slug: string) {
  return techPages.find((item) => item.slug === slug) ?? null;
}
